market_place/article/urls.py
from django.conf.urls import url
from article import views

urlpatterns = [
	url(r'^new$', views.New.as_view(), name='new'),
	url(r'^view/(?P<article_id>[0-9]+)$', views.ViewArticle.as_view(), name='view'),
	url(r'^view$', views.ViewArticle.as_view(), name='view')
]

market_place/market_place/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^public/', include('public.urls', namespace="public")),
    url(r'^users/', include('users.urls', namespace="users")),
    url(r'^article/', include('article.urls', namespace="article"))
]

market_place/market_place_app/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index')
]

market_place/users/urls.py
from django.conf.urls import url
from users import views

urlpatterns = [
	url(r'^profile$', views.Index.as_view(), name='profile'),
	url(r'^profile/(?P<username>[a-zA-Z0-9]+)$', views.ViewProfile.as_view(), name='view'),
	url(r'^change_password$', views.ChangePassword.as_view(), name="change_password")
]

market_place/article/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from public.models import Article

from django.db import models

# Create your models here.
class UserBid(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	article = models.ForeignKey(Article, on_delete=models.CASCADE)
	current_bid = models.DecimalField(default=0, max_digits=9, decimal_places=2)
	maximum_bid = models.DecimalField(default=0, max_digits=9, decimal_places=2, null=True)
	created_date = models.DateTimeField(auto_now=True)
	last_bid_date = models.DateTimeField()
	is_smart_bid = models.BooleanField(default=True)

market_place/market_place_app/models.py
from django.db import models

# Create your models here.

market_place/users/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User

from django.db import models

class UserProfile(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	address = models.CharField(max_length=128, null=True, blank=True)
	date_of_birth = models.DateTimeField(null=True, blank=True, default=None)
	picture_path = models.CharField(max_length=128, null=True, blank=True)
	followers = models.ManyToManyField(User, related_name='user_followers')

market_place/article/views.py
from django.shortcuts import render, redirect
from django.db.models import Max
from django.views.generic import View
from public.models import Article
from models import UserBid
import datetime

from public.code.layout_util import get_layout_context
from code.article_util import save_article, save_user_bid
# Create your views here.

ARTICLE_CONDITIONS = {
	1: "New",
	2: "Used"
}

class New(View):
	def get(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect('/public/signin')
		context = get_layout_context(request, None)
		context['conditions'] = ARTICLE_CONDITIONS.items()
		return render(request, 'article/new.html', context)

	def post(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect('/public/signin')
		article_id = save_article(request)
		if article_id == None:
			article_id = 0
		return redirect('view/{0}'.format(article_id))


class ViewArticle(View):
	def get(self, request, article_id, *args, **kwargs):
		context = get_layout_context(request, None)
		try:
			article = Article.objects.get(pk=article_id)
			context['article'] = article
			highest_bids = UserBid.objects.filter(article=article).order_by('-current_bid')
			if len(highest_bids) > 0:
				highest_bid = highest_bids[0]
				context['highest_bid'] = highest_bid
			
			article.condition_name = ARTICLE_CONDITIONS[article.condition]
			article.can_place_bid = request.user.is_authenticated() and request.user.username != article.created_by.username
			article.picture_url = 'public/upload/no-image.png'
		except Exception, e:
			raise e
		return render(request, 'article/view.html', context)

	def post(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect('/public/signin')
		save_user_bid(request)
		return redirect('view/{0}'.format(request.POST.get('article_id')))

market_place/market_place_app/views.py
from django.shortcuts import render
from django.http import HttpResponse

def index(request):
	return HttpResponse("Is it working?")

# Create your views here.

market_place/users/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from django.contrib.auth.models import User
from django.contrib.auth import authenticate

from public.models import Category
from .models import UserProfile
from .view_models import ProfileEditViewModel, ChangePasswordViewModel
from public.code.layout_util import get_layout_context
from users.code.user_profile_util import save_user_profile

class Index(View):

	def get(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect('/public/signin')

		context = get_layout_context(request, 'users/profile');

		try:
			user_profile = UserProfile.objects.get(user__username=request.user.username);
		except (KeyError, UserProfile.DoesNotExist):
			user = User.objects.get(username=request.user.username)
			user_profile = UserProfile(user=user)
			user_profile.save()

		if user_profile.picture_path:
			user_profile.picture_url = 'public/upload/users/{0}/{1}'.format(request.user.username, user_profile.picture_path)
		else:
			user_profile.picture_url = 'public/upload/no_profile.png'
		context['user_profile'] = user_profile
		return render(request, 'users/index.html', context)

	def post(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect('/public/signin')
		context = get_layout_context(request, 'users/profile')
		user_profile = save_user_profile(request)
		if user_profile:
			if user_profile.picture_path:
				user_profile.picture_url = 'public/upload/users/{0}/{1}'.format(request.user.username, user_profile.picture_path)
			else:
				user_profile.picture_url = 'public/upload/no_profile.png'
			context['user_profile'] = user_profile
		return render(request, 'users/index.html', context)


class ViewProfile(View):

	def get(self, request, username, *args, **kwargs):
		context = get_layout_context(request, None)
		try:
			user_profile = UserProfile.objects.get(user__username=username)
			if user_profile.picture_path:
				user_profile.picture_url = 'public/upload/users/{0}/{1}'.format(username, user_profile.picture_path)
			else:
				user_profile.picture_url = 'public/upload/no_profile.png'
			context['user_profile'] = user_profile
		except Exception, e:
			pass

		return render(request, 'users/view.html', context)


class ChangePassword(View):

	def post(self, request, *args, **kwargs):
		if not request.user.is_authenticated():
			return redirect('/public/signin')
		view_model = ChangePasswordViewModel(data=request.POST)
		context = get_layout_context(request, 'users/profile')
		if view_model.is_valid():
			user = User.objects.get(username=request.user.username)
			if authenticate(username=request.user.username, password=view_model.cleaned_data['old_password']) is None:
				context['change_password_error'] = 'Old password is wrong!'
			elif view_model.cleaned_data['new_password'] != view_model.cleaned_data['repeat_new_password']:
				context['change_password_error'] = 'New password and repeat new password must match!'
			else:
				user.set_password(view_model.cleaned_data['new_password'])
				user.save()
		user_profile = UserProfile.objects.get(user__username=request.user.username)
		if user_profile.picture_path:
			user_profile.picture_url = 'public/upload/users/{0}/{1}'.format(request.user.username, user_profile.picture_path)
		else:
			user_profile.picture_url = 'public/upload/no_profile.png'
		context['user_profile'] = user_profile
		return render(request, 'users/index.html', context)

market_place/article/templates/article/new.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
	<h2>New article</h2>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Basic information</h3>
		</div>
		<div class="panel-body">
			<form class="form-horizontal" action="{% url 'article:new' %}" method="post">
				{% csrf_token %}
				<div class="form-group">
					<label for="title" class="col-sm-2 control-label">Title</label>
					<div class="col-sm-6">
						<input type="text" class="form-control" id="title" name="title" required />
					</div>
				</div>
				<div class="form-group">
					<label for="category" class="col-sm-2 control-label">Category</label>
					<div class="col-sm-6">
	    				<select id="category" name="category" class="form-control">
	    					{% if top_categories %}
    							{% for top_category in top_categories %}
    								<option value="{{ top_category.id }}">{{ top_category.name }}</option>
    							{% endfor %}
	    					{% endif %}
	    				</select>
					</div>
				</div>
				<div class="form-group">
					<label for="description" class="col-sm-2 control-label">Description</label>
					<div class="col-sm-6">
						<textarea class="form-control" id="description" name="description" ></textarea>
					</div>
				</div>
				<div class="form-group">
					<label for="starting_price" class="col-sm-2 control-label">Starting price</label>
					<div class="col-sm-6">
						<div class="input-group">
							<span class="input-group-addon">$</span>
							<input type="number" class="form-control" id="starting_price" name="starting_price" required/>
						</div>
					</div>
				</div>
				<div class="form-group">
					<label for="buyout_price" class="col-sm-2 control-label">Buyout price</label>
					<div class="col-sm-6">
						<div class="input-group">
							<span class="input-group-addon">$</span>
							<input type="number" class="form-control" id="buyout_price" name="buyout_price" required/>
						</div>
					</div>
				</div>
				<div class="form-group">
					<label for="condition" class="col-sm-2 control-label">Condition</label>
					<div class="col-sm-6">
	    				<select id="condition" name="condition" class="form-control">
	    					{% if conditions %}
    							{% for id, name in conditions %}
    								<option value="{{ id }}">{{ name }}</option>
    							{% endfor %}
	    					{% endif %}
	    				</select>
					</div>
				</div>
				<div class="form-group">
					<label for="expiry_date" class="col-sm-2 control-label">Expiry date</label>
					<div class="col-sm-6">
						<input type="datetime-local" class="form-control" id="expiry_date" name="expiry_date" required/>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-12">
						<button type="submit" class="btn btn-primary">Create</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

market_place/article/templates/article/view.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
	<h2>View article</h2>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Basic information</h3>
		</div>
		<div class="panel-body">
			<form class="form-horizontal" action="{% url 'article:view'  %}" method="post">
				{% csrf_token %}
				<div class="row">
					<div class="col-sm-6">
						{% load staticfiles %}
						<img style="width: 100%" src="{% static article.picture_url %}" class="img-rounded" />
					</div>
					<div class="col-sm-6">
						<div class="form-group">
						<label class="col-sm-4 control-label">Title</label>
						<div class="col-sm-8">
							<p class="form-control-static">{{ article.title }}</p>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Category</label>
						<div class="col-sm-8">
							<p class="form-control-static">{{ article.category.name }}</p>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Description</label>
						<div class="col-sm-8">
							<p class="form-control-static" >{{ article.description }}</p>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Highest bid</label>
						<div class="col-sm-8">
							<div class="input-group">
								<p class="form-control-static">$ {{ article.starting_price }}</p>
							</div>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Buyout price</label>
						<div class="col-sm-8">
							<div class="input-group">
								<p class="form-control-static">$ {{ article.buyout_price }}</p>
							</div>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-4 control-label">Highest bidder</label>
						<div class="col-sm-8">
							<div class="input-group">
								<p class="form-control-static">
									{% if highest_bid %}
										{{ highest_bid.user.username }}  with $ {{ highest_bid.current_bid }}
									{% else %}
										No bids yet!
									{% endif %}
								</p>
							</div>
						</div>
					</div>
					<div class="form-group">
						<label for="condition" class="col-sm-4 control-label">Condition</label>
						<div class="col-sm-8">
		    				<p class="form-control-static">{{ article.condition_name }}</p>
						</div>
					</div>
					<div class="form-group">
						<label for="expiry_date" class="col-sm-4 control-label">Expiry date</label>
						<div class="col-sm-8">
							<p class="form-control-static">{{ article.expiry_date|date:'d.m.Y H:i' }}</p>
						</div>
					</div>
					{% if article.can_place_bid and article.active %}
						<div class="form-group">
							<label for="bid" id="lbl_your_bid" class="col-sm-4 control-label">Your bid</label>
							<div class="col-sm-6">
								<div class="input-group">
									<span class="input-group-addon">$</span>
									<input type="number" class="form-control" id="bid" name="bid" required />
								</div>
							</div>
						</div>
						<div class="form-group">
							<label for="is_smart_bid"  class="col-sm-4 control-label">Smart bid</label>
							<div class="col-sm-8">	
								<input type="checkbox" id="is_smart_bid" name="is_smart_bid" style="margin-top: 9px"/>
							</div>
						</div>
						<div class="form-group">
							<div class="col-sm-12">
								<button type="submit" class="btn btn-primary">Place bid</button>
							</div>
						</div>
					{% endif %}
					</div>
				</div>
				
				{% if username == article.created_by.username %}
					<div class="form-group">
						<div class="col-sm-12">
							<a href="#" class="btn btn-primary">Edit</a>
						</div>
					</div>
				{% endif %}
				<input type="text" id="article_id" name="article_id" style="display: none" value="{{ article.id }}"/>
			</form>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Comments</h3>
		</div>
		<div class="panel-body">
			{% if article.comments %}
			{% else %}
				<div class="well">
					No comments available!
				</div>
			{% endif %}
			<form class="form-horizontal" style="display: none">

			</form>
			<button type="button" class="btn btn-primary">Add comment</button>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function(){
		$('#is_smart_bid').on('click', function(event){
			if (this.checked) {
				$('#lbl_your_bid').text('Maximum bid')
			}
			else {
				$('#lbl_your_bid').text('Your bid')
			}
		})
	})
</script>
{% endblock %}

market_place/market_place/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'public/bootstrap.min.css' %}"/>

	<script src="{% static 'public/jquery-2.2.4.js' %}"></script>
	<script src="{% static 'public/bootstrap.min.js' %}"></script>
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header" style="width: 8%">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#layout-navbar-collapse" aria-expanded="false">
	        	<span class="sr-only">Toggle navigation</span>
	        	<span class="icon-bar"></span>
	        	<span class="icon-bar"></span>
	        	<span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="#">
		      	<img src="{% static 'public/upload/market_place_logo.png' %}" style="position: relative;width: 50%;top: -12px;left: -12px;" />
		      </a>
		    </div>
	    	<div class="collapse navbar-collapse" id="layout-navbar-collapse">
	    		<ul class="nav navbar-nav">
	    			<li class="{% if active_view == 'public/index' %}active{%endif%}">
	    				<a href="{% url 'public:index' %}">Home</a>
	    			</li>
	    			{% if is_authenticated %}
		    			<li class="{% if active_view == 'users/profile' %}active{%endif%}">
		    				<a href="{% url 'users:profile' %}">Profile</a>
		    			</li>
	    			{% endif %}
	    			{% if can_create_articles %}
		    			<li class="dropdown">
		    				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
		    					Article <span class="caret"></span>
		    					<ul class="dropdown-menu">
		    						<li>
		    							<a href="{% url 'article:new' %}">Create article</a>
		    						</li>
		    						<li>
		    							<a href="#">My articles</a>
		    						</li>
		    					</ul>
		    				</a>
		    			</li>
	    			{% endif %}
	    			<li class="dropdown">
	    				<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
	    					Categories <span class="caret"></span>
	    					{% if top_categories %}
	    						<ul class="dropdown-menu">
	    							{% for top_category in top_categories %}
	    								<li>
	    									<a href="#">{{ top_category.name }}</a>
	    								</li>
	    							{% endfor %}
	    						</ul>
	    					{% endif %}
	    				</a>
	    			</li>
	    		</ul>
	    		<div class="navbar-right">
	    		{% if is_authenticated %}
	    			<p class="navbar-text">Signed in as {{ username }}</p>
	    			<a href="{% url 'public:signout' %}" class="btn btn-default navbar-btn">Sign out</a>
	    		{% else %}
	    			<a href="{% url 'public:signin' %}" class="btn btn-default navbar-btn">Sign in</a>
	    		{% endif %}
	    		</div>
	    		<form class="navbar-form navbar-right" role="search">
	    			<div class="form-group">
				      	<input type="text" class="form-control" placeholder="Search">
				    </div>
				    <button type="submit" class="btn btn-default">Submit</button>
	    		</form>
	    	</div>
		</div>
	</nav>
	<div>
		{% block content %}{% endblock %}
	</div>
</body>
</html>

market_place/users/templates/users/index.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
	<h2>Profile</h2>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Basic information</h3>
		</div>
		<div class="panel-body">
			<div class="row" style="margin-bottom: 15px">
				{% load staticfiles %}
				<div class="col-sm-offset-2 col-sm-2">
					<img id="profile_picture" src="{% static user_profile.picture_url %}" class="img-circle" style="width: 100%; cursor: pointer" />
				</div>
			</div>
			<form class="form-horizontal" action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
				<input type="file" class="form-control" id="picture" name="picture" style="display: none" />
				{% csrf_token %}
				<div class="form-group">
					<label for="first_name" class="col-sm-2 control-label">First name</label>
					<div class="col-sm-6">
						<input type="text" class="form-control" id="first_name" name="first_name" value="{{ user_profile.user.first_name }}" />
					</div>
				</div>
				<div class="form-group">
					<label for="last_name" class="col-sm-2 control-label">Last name</label>
					<div class="col-sm-6">
						<input type="text" class="form-control" id="last_name" name="last_name" value="{{ user_profile.user.last_name }}" />
					</div>
				</div>
				<div class="form-group">
					<label for="email" class="col-sm-2 control-label">Email</label>
					<div class="col-sm-6">
						<input type="text" class="form-control" id="email" name="email" value="{{ user_profile.user.email }}" />
					</div>
				</div>
				<div class="form-group">
					<label for="address" class="col-sm-2 control-label">Address</label>
					<div class="col-sm-6">
						<input type="text" class="form-control" id="address" name="address" value="{{ user_profile.address }}" />
					</div>
				</div>
				<div class="form-group">
					<label for="date_of_birth" class="col-sm-2 control-label">Date of birth</label>
					<div class="col-sm-6">
						<input type="date" class="form-control" id="date_of_birth" name="date_of_birth" value="{{ user_profile.date_of_birth|date:'Y-m-d' }}" />
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-12">
						<button type="submit" class="btn btn-primary">Save</button>
					</div>
				</div>
			</form>
		</div>
	</div>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Change password</h3>
		</div>
		<div class="panel-body">
			<form class="form-horizontal" action="{% url 'users:change_password' %}" method="post">
				{% if change_password_error %}
					<div class="alert alert-danger alert-dismissible" role="alert">
						<button type="button" class="close" aria-label="Close"><span aria-hidden="true">&times;</span></button>
						<strong>Error!</strong> {{ change_password_error }}
					</div>
				{% endif %}
				{% csrf_token %}
				<div class="form-group">
					<label for="old_password" class="col-sm-2 control-label">Old password</label>
					<div class="col-sm-6">
						<input type="password" class="form-control" id="old_password" name="old_password" required />
					</div>
				</div>
				<div class="form-group">
					<label for="new_password" class="col-sm-2 control-label">New password</label>
					<div class="col-sm-6">
						<input type="password" class="form-control" id="new_password" name="new_password" required />
					</div>
				</div>
				<div class="form-group">
					<label for="repeat_new_password" class="col-sm-2 control-label">Repeat new password</label>
					<div class="col-sm-6">
						<input type="password" class="form-control" id="repeat_new_password" name="repeat_new_password" required />
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-12">
						<button type="submit" class="btn btn-primary">Change password</button>
					</div>
				</div>
			</form>
		</div>
	</div>
</div>
<script	type="text/javascript">
	$(document).ready(function() {
		$('#profile_picture').on('click', function(){
			$('#picture').click();
		});
	});
</script>
{% endblock %}

market_place/users/templates/users/view.html
{% extends 'layout.html' %}
{% block content %}
<div class="container">
	<h2>Profile</h2>
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title">Basic information</h3>
		</div>
		<div class="panel-body">
			<div class="row" style="margin-bottom: 15px">
				{% load staticfiles %}
				<div class="col-sm-offset-2 col-sm-2">
					<img id="profile_picture" src="{% static user_profile.picture_url %}" class="img-circle" style="width: 100%;" />
				</div>
			</div>
			<form class="form-horizontal">
				<div class="form-group">
					<label class="col-sm-2 control-label">First name</label>
					<div class="col-sm-6">
						<p class="form-control-static">{{ user_profile.user.first_name }}</p>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Last name</label>
					<div class="col-sm-6">
						<p class="form-control-static">{{ user_profile.user.last_name }}</p>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Email</label>
					<div class="col-sm-6">
						<p class="form-control-static">{{ user_profile.user.email }}</p>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Address</label>
					<div class="col-sm-6">
						<p class="form-control-static">{{ user_profile.address }}</p>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Date of birth</label>
					<div class="col-sm-6">
						<p class="form-control-static">{{ user_profile.date_of_birth|date:'m/d/Y' }}</p>
					</div>
				</div>
				<div class="form-group">
					<div class="col-sm-12">
						<button type="submit" class="btn btn-primary">Follow</button>
					</div>
				</div>
			</form>
		</div>
	</div>	
</div>
{% endblock %}